name = "Spellbound Skies - Beta 1.1.0"
author = "kuzhcola"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b825b439a851bc9c0c00fe1dd41cc102c3d86639891031b61ef715421ad655cb"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.3"
