name = "Spellbound Skies - Beta 1.1.0"
author = "kuzhcola"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d2b47e5df56f4fe35b606fb7452244fbc6fbca42cb9e19f2aef77b83931a9f6"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
unsup = "1.1.3"
