
["Client Configs for Tinker's Tool Leveling 2"]
	#The multiplier for the exp granted to a mining tool after each block break. Default is 1.0
	"Exp Per Block" = 1.0
	#The multiplier for the exp granted to a melee weapon after each block break. Default is 1.0
	"Exp Per Melee Kill" = 1.0
	#The multiplier for the exp granted to an armor piece after each block break. Default is 1.0
	"Exp Per Armor Hit" = 1.0
	#Whether or not breaking bedrock gives 100,000 exp for a mining tool. Primarily used for admin purposes. Default is true
	"Admin Exp" = true
	#The amount of levels between each bonus modifier. Set to 0 to disable bonus modifiers. Default is 3
	#Range: 0 ~ 11
	"Levels Between Bonus Modifiers" = 3
	#The base exp required to level up a tool. Default is 500
	#Range: > 1
	"Exp Required" = 500

