#If true, the Glitch Armor will allow creative flight.
isGlitchArmorCreativeFlightEnabled = true
#If true, the Glitch Armor will drop extra items when breaking blocks.
isGlitchArmorExtraDropsEnabled = true

